baseurl = "https://defitonyportfolio.vercel.app/"
title = "Tony Legend - Portfolio"
languageCode = "en-us"
defaultContentLanguage = "en"
publishDir = "public"
outputs = {page = ["HTML"]}

[params]
  description = "Full-stack developer, designer, and creator"
  author = "Tony Legend"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
